import React from 'react'
import Head from 'next/head'
import { motion } from 'framer-motion'
import Header from '../../../components/Header'

const About = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* Slider Part */}
      <div className="slider h-96 bg-slate-600">
        <motion.div
          animate={{ x: 100 }}
          initial={{ x: 0 }}
          transition={{ duration: 1 }
          }>
          This is my animated element.
        </motion.div>
        <div className='container mx-96'>
          <h1 className='font-medium' >Protfolio</h1>
          
        </div>
      </div>
      <h1>About Page</h1>
    </>
  )
}

export default About
