import React from "react";
import Head from "next/head";
import { motion } from "framer-motion";
import Header from "../../../components/Header";
import Link from "next/link";
import Clients from "../../../components/Clients ";
import Image from "next/image";

const Survices = () => {
  const container = {
    hidden: { opacity: 1, scale: 0 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        delayChildren: 0.3,
        staggerChildren: 0.2,
      },
    },
  };
  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  };

  const num = [0, 1, 2, 3, 4];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      {/* Slider Part */}
      <div className="section">
        <div className="container mx-auto">
          <div className="md:h-[100vh] flex flex-col items-center justify-center">
            <div className="md:flex w-full">
              <div className="w-full  md:h-full flex flex-col justify-center py-24 mt-10 px-5 md:px-0">
                <motion.h1
                  initial={{ translateX: -250 }}
                  transition={{ duration: 0.5 }}
                  whileInView={{ translateX: 0 }}
                  className="text-6xl md:text-7xl font-bold"
                >
                  Hy! Am <br />{" "}
                  <span className="text-orange-500">Maruf Subonro</span>
                </motion.h1>
                <motion.p
                  initial={{ translateX: -250 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                  whileInView={{ translateX: 0 }}
                  className="w-[80%] my-5"
                >
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
                  labore quia incidunt! Molestiae nam tempora maiores.
                  Distinctio earum iusto aspernatur!
                </motion.p>
                <motion.div
                  initial={{ scale: 0 }}
                  transition={{ duration: 0.5, delay: 0.4 }}
                  whileInView={{ scale: 1 }}
                >
                  <Link
                    href={"/contact"}
                    className="btn bg-gradient-to-r from-amber-500 to-amber-400 shadow-lg shadow-yellow-500/80 hover:scale-105 transition-all cursor-pointer p-2 px-6 rounded-full text-white"
                  >
                    Hire me
                  </Link>
                </motion.div>
              </div>
              <div className="relative w-full md:h-full pt-10 px-5 md:px-0">
              <motion.div
                  initial={{ scale: 0.8 }}
                  transition={{ duration: 0.5, delay: 0.4 }}
                  whileInView={{ scale: 1 }}
                  >
                  <Image src="/hero-image.png" alt="hero image" width={700} height={700} />
                  </motion.div>
                  <motion.div 
                  initial={{ translateX: 250 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                  whileInView={{ translateX: 0 }}
                  className="absolute -top-[5%] md:top-[20%] right-0">
                  <div className="card flex items-center bg-white shadow-xl scale-75 hover:scale-100 transition-all cursor-pointer p-5 rounded-lg">
                    <div className="w-10 h-10 grid place-content-center rounded-full bg-pink-200">UI</div>
                    <div className="flex flex-col items-start ml-5">
                      <strong>UI/UX</strong>
                      <p className="w-[250px]">Lorem ipsum dolor sit amet consectetur.</p>
                    </div>
                  </div>
                  </motion.div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Survices;
